#!/usr/bin/env bash
# generate-slurm-scripts.sh — writes the nine *.slurm job scripts (setup, containers, databases,
# annotate, annotate-classify, annotate-downstream, run-meta, gtdbtk-highmem, llm) to
# accessory-files/slurm/ from the SLURM settings in pipeline.conf.sh section 9.
# Run by setup.sh (or ./setup.sh --generate-slurm); the output is gitignored.
set -euo pipefail

_here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$_here/../../.." && pwd)"
SLURM_DIR="$REPO_ROOT/accessory-files/slurm"

# shellcheck source=../../../pipeline.conf.sh
source "$REPO_ROOT/pipeline.conf.sh"

# Without an allocation there is nothing valid to write (a computer without SLURM needs none).
if [[ -z "${SLURM_ACCOUNT:-}" ]]; then
    printf '[generate-slurm] SLURM_ACCOUNT is not set in pipeline.conf.sh section 9: no job scripts written\n'
    exit 0
fi

# Writes stdin to accessory-files/slurm/<name> and makes it executable.
_write() {
    local dest="$SLURM_DIR/$1"
    cat > "$dest"
    chmod +x "$dest"
    printf '[generate-slurm] wrote accessory-files/slurm/%s\n' "$1"
}

# ── 1. containers.slurm ───────────────────────────────────────────────────────
_write containers.slurm <<SLURM
#!/bin/bash
# GENERATED by generate-slurm-scripts.sh — do not edit by hand.
# To change settings, edit pipeline.conf.sh section 9, then run:
#   ./setup.sh --generate-slurm
#SBATCH --job-name=margie-containers
#SBATCH --account=${SLURM_ACCOUNT}
#SBATCH --partition=${SLURM_PARTITION}
#SBATCH --nodes=${SLURM_CONTAINERS_NODES}
#SBATCH --time=${SLURM_CONTAINERS_TIME}
#SBATCH --output=logs/containers/slurm-%j.out
#SBATCH --error=logs/containers/slurm-%j.err

# containers.slurm — pull/build container images only.
# Submit:              sbatch containers.slurm
# Restrict to one tool: sbatch containers.slurm --tool pfam
set -euo pipefail

cd "\$SLURM_SUBMIT_DIR"
mkdir -p logs/containers

module load apptainer 2>/dev/null || module load singularity 2>/dev/null || true

# Gated tools (merops tcdb tmbed interpro phobius psortb) are set up
# only with the licence statement: set LICENCE_INTENDED_USE and LICENCE_STATEMENT
# in pipeline.conf.sh section 8 (or type it in ./setup.sh at a terminal first).
# Without it --accept-all-licences accepts nothing and they are skipped.
./setup.sh --containers-only --accept-all-licences "\$@"
SLURM

# ── 2. databases.slurm ───────────────────────────────────────────────────────
_write databases.slurm <<SLURM
#!/bin/bash
# GENERATED by generate-slurm-scripts.sh — do not edit by hand.
# To change settings, edit pipeline.conf.sh section 9, then run:
#   ./setup.sh --generate-slurm
#SBATCH --job-name=margie-databases
#SBATCH --account=${SLURM_ACCOUNT}
#SBATCH --partition=${SLURM_PARTITION}
#SBATCH --nodes=${SLURM_DATABASES_NODES}
#SBATCH --time=${SLURM_DATABASES_TIME}
#SBATCH --output=logs/databases/slurm-%j.out
#SBATCH --error=logs/databases/slurm-%j.err

# databases.slurm — download all reference databases (excludes llm).
# Submit:                sbatch databases.slurm
# Restrict to one tool:  sbatch databases.slurm --tool kegg
# NOTE: LLM model weights are not part of the automated database set.
#       Use llm.slurm for the LLM model download (requires HF token).
set -euo pipefail

cd "\$SLURM_SUBMIT_DIR"
mkdir -p logs/databases

module load apptainer 2>/dev/null || module load singularity 2>/dev/null || true

# Gated tools (merops tcdb tmbed interpro phobius psortb) are set up
# only with the licence statement: set LICENCE_INTENDED_USE and LICENCE_STATEMENT
# in pipeline.conf.sh section 8 (or type it in ./setup.sh at a terminal first).
# Without it --accept-all-licences accepts nothing and they are skipped.
./setup.sh --databases-only --accept-all-licences "\$@"
SLURM

# ── 3. setup.slurm ───────────────────────────────────────────────────────────
_write setup.slurm <<SLURM
#!/bin/bash
# GENERATED by generate-slurm-scripts.sh — do not edit by hand.
# To change settings, edit pipeline.conf.sh section 9, then run:
#   ./setup.sh --generate-slurm
#SBATCH --job-name=margie-setup
#SBATCH --account=${SLURM_ACCOUNT}
#SBATCH --partition=${SLURM_PARTITION}
#SBATCH --nodes=${SLURM_SETUP_NODES}
#SBATCH --time=${SLURM_SETUP_TIME}
#SBATCH --output=logs/setup/slurm-%j.out
#SBATCH --error=logs/setup/slurm-%j.err

# setup.slurm — full setup: build/pull containers AND download databases.
# Submit:  sbatch setup.slurm
# NOTE: LLM model weights are NOT included. Use llm.slurm separately.
set -euo pipefail

cd "\$SLURM_SUBMIT_DIR"
mkdir -p logs/setup

module load apptainer 2>/dev/null || module load singularity 2>/dev/null || true

# Gated tools (merops tcdb tmbed interpro phobius psortb) are set up
# only with the licence statement: set LICENCE_INTENDED_USE and LICENCE_STATEMENT
# in pipeline.conf.sh section 8 (or type it in ./setup.sh at a terminal first).
# Without it --accept-all-licences accepts nothing and they are skipped.
./setup.sh --accept-all-licences "\$@"
SLURM

# ── 4. annotate.slurm ────────────────────────────────────────────────────────
_write annotate.slurm <<SLURM
#!/bin/bash
# GENERATED by generate-slurm-scripts.sh — do not edit by hand.
# To change settings, edit pipeline.conf.sh section 9, then run:
#   ./setup.sh --generate-slurm
#SBATCH --job-name=annotate
#SBATCH --account=${SLURM_ACCOUNT}
#SBATCH --partition=${SLURM_PARTITION}
#SBATCH --nodes=${SLURM_ANNOTATE_NODES}
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=${SLURM_ANNOTATE_CPUS}
#SBATCH --mem=${SLURM_ANNOTATE_MEM}
#SBATCH --time=${SLURM_ANNOTATE_TIME}
#SBATCH --output=logs/annotation/slurm-%j.out
#SBATCH --error=logs/annotation/slurm-%j.err

# annotate.slurm — run the annotation pipeline on input genomes.
# Submit:               sbatch annotate.slurm
# Restrict to one tool: sbatch annotate.slurm --tool pfam
set -euo pipefail

cd "\$SLURM_SUBMIT_DIR"
mkdir -p logs/annotation

module load apptainer 2>/dev/null || module load singularity 2>/dev/null || true

export THREADS=\${SLURM_CPUS_PER_TASK:-${SLURM_ANNOTATE_CPUS}}

./annotate.sh "\$@"
SLURM

# ── 5. llm.slurm ─────────────────────────────────────────────────────────────
_write llm.slurm <<SLURM
#!/bin/bash
# GENERATED by generate-slurm-scripts.sh — do not edit by hand.
# To change settings, edit pipeline.conf.sh section 9, then run:
#   ./setup.sh --generate-slurm
#SBATCH --job-name=margie-llm-download
#SBATCH --account=${SLURM_ACCOUNT}
#SBATCH --partition=${SLURM_PARTITION}
#SBATCH --nodes=${SLURM_LLM_NODES}
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=${SLURM_LLM_CPUS}
#SBATCH --mem=${SLURM_LLM_MEM}
#SBATCH --time=${SLURM_LLM_TIME}
#SBATCH --output=logs/databases/llm/slurm-%j.out
#SBATCH --error=logs/databases/llm/slurm-%j.err

# llm.slurm — download LLM model weights into \$DB_ROOT/llm/base/
#             (large file, ~16 GB for Llama-3 8B; run as a dedicated job).
#
# BEFORE SUBMITTING — cache a HuggingFace token interactively on a login node:
#   ./setup.sh --databases-only --tool llm
#   # Enter your token at the prompt, then Ctrl+C to exit without downloading.
#   # Token is saved to processing/.hf-env/hf_token (chmod 600, local only).
#   # After the download finishes, revoke the token at:
#   #   https://huggingface.co/settings/tokens
#
# Also ensure LLM_BASE_MODEL is set in pipeline.conf.sh (section 6).
#
# Submit:
#   sbatch llm.slurm           (download configured model)
#   sbatch llm.slurm --redo    (delete existing weights and re-download)
set -euo pipefail

cd "\$SLURM_SUBMIT_DIR"
mkdir -p logs/databases/llm

# Fail fast if the token is missing — the token must already be cached.
# Fail fast here with a clear message rather than a silent skip.
_tok_file="processing/.hf-env/hf_token"
if [[ ! -s "\$_tok_file" ]]; then
    printf '[llm.slurm] ERROR: No HuggingFace token cached at %s\n' "\$_tok_file" >&2
    printf '[llm.slurm]        Cache a token interactively BEFORE submitting this job:\n' >&2
    printf '[llm.slurm]          ./setup.sh --databases-only --tool llm  (on a login node)\n' >&2
    printf '[llm.slurm]          # Enter token at prompt, then Ctrl+C to exit.\n' >&2
    exit 1
fi

module load apptainer 2>/dev/null || module load singularity 2>/dev/null || true

# Tell hf-env.sh not to wait for interactive input — job must fail clearly
# rather than hang if the token is missing or has been revoked.
export HF_NONINTERACTIVE=1

./setup.sh --databases-only --tool llm "\$@"
SLURM

# ── 6. annotate-classify.slurm ───────────────────────────────────────────────
_write annotate-classify.slurm <<SLURM
#!/bin/bash
# GENERATED by generate-slurm-scripts.sh — do not edit by hand.
# To change settings, edit pipeline.conf.sh section 9, then run:
#   ./setup.sh --generate-slurm
#SBATCH --job-name=annotate-classify
#SBATCH --account=${SLURM_ACCOUNT}
#SBATCH --partition=${SLURM_PARTITION}
#SBATCH --nodes=${SLURM_CLASSIFY_NODES}
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=${SLURM_CLASSIFY_CPUS}
#SBATCH --mem=${SLURM_CLASSIFY_MEM}
#SBATCH --time=${SLURM_CLASSIFY_TIME}
#SBATCH --output=logs/annotation/annotate-classify-%j.out
#SBATCH --error=logs/annotation/annotate-classify-%j.err

# annotate-classify.slurm — run GTDB-Tk on user-input/ genomes and write the
# genome table input/genomes.tsv (domain, genetic code, gene caller) plus the
# taxonomy report input/classification_report.tsv.
#
# Submit:
#   sbatch accessory-files/slurm/annotate-classify.slurm
# Optional extra arguments:
#   sbatch accessory-files/slurm/annotate-classify.slurm -- --list
set -euo pipefail

cd "\$SLURM_SUBMIT_DIR"
mkdir -p logs/annotation

module load apptainer 2>/dev/null || module load singularity 2>/dev/null || true

export THREADS="\${SLURM_CPUS_PER_TASK:-${SLURM_CLASSIFY_CPUS}}"

if [[ "\${1:-}" == "--" ]]; then
    shift
fi

RUN_GTDBTK=1 ./annotate.sh --prepare-only "\$@"
SLURM

# ── 7. annotate-downstream.slurm ─────────────────────────────────────────────
_write annotate-downstream.slurm <<SLURM
#!/bin/bash
# GENERATED by generate-slurm-scripts.sh — do not edit by hand.
# To change settings, edit pipeline.conf.sh section 9, then run:
#   ./setup.sh --generate-slurm
#SBATCH --job-name=margie-annotate-downstream
#SBATCH --account=${SLURM_ACCOUNT}
#SBATCH --partition=${SLURM_PARTITION}
#SBATCH --nodes=${SLURM_DOWNSTREAM_NODES}
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=${SLURM_DOWNSTREAM_CPUS}
#SBATCH --mem=${SLURM_DOWNSTREAM_MEM}
#SBATCH --time=${SLURM_DOWNSTREAM_TIME}
#SBATCH --output=logs/annotation/downstream-%j.out
#SBATCH --error=logs/annotation/downstream-%j.err

# annotate-downstream.slurm — run annotation tool containers on existing gene calls.
# Skips gene calling; processes all genomes found in output/rasttk/.
# 6 tools run in parallel (PARALLEL_TOOLS); gram-agnostic tools finish, then
# the envelope stage infers each genome's envelope from tigrfam / pgap / pfam /
# uniprot, then the gram-dependent tools (psortb, deepsig, signalp4) start.
#
# Submit:               sbatch accessory-files/slurm/annotate-downstream.slurm
# Restrict to one tool: sbatch accessory-files/slurm/annotate-downstream.slurm --tool pfam
set -euo pipefail

cd "\$SLURM_SUBMIT_DIR"
mkdir -p logs/annotation

module load apptainer 2>/dev/null || module load singularity 2>/dev/null || true

export THREADS=\${SLURM_CPUS_PER_TASK:-${SLURM_DOWNSTREAM_CPUS}}

source ./pipeline.conf.sh

runner="./processing/scripts/run-individual-containers"

filter_tools=()
while [[ \$# -gt 0 ]]; do
    case "\$1" in
        --tool)   filter_tools+=("\$2"); shift 2 ;;
        --tool=*) filter_tools+=("\${1#--tool=}"); shift ;;
        *) echo "unknown option: \$1" >&2; exit 2 ;;
    esac
done

pre_tools=(kegg cog pfam pgap tigrfam dbcan eggnog merops tcdb uniprot interpro geneprop tmbed phobius operon)
post_tools=(psortb deepsig signalp4)
envelope_inputs=(tigrfam pgap pfam uniprot)

if (( \${#filter_tools[@]} )); then
    filtered_pre=()
    filtered_post=()
    for t in "\${pre_tools[@]}";  do [[ " \${filter_tools[*]} " == *" \$t "* ]] && filtered_pre+=("\$t");  done
    for t in "\${post_tools[@]}"; do [[ " \${filter_tools[*]} " == *" \$t "* ]] && filtered_post+=("\$t"); done
    pre_tools=("\${filtered_pre[@]+"\${filtered_pre[@]}"}")
    post_tools=("\${filtered_post[@]+"\${filtered_post[@]}"}")
    # the envelope stage reads these, so gram-dependent tools bring them along
    if (( \${#post_tools[@]} )); then
        for t in "\${envelope_inputs[@]}"; do
            [[ " \${pre_tools[*]} " == *" \$t "* ]] || pre_tools+=("\$t")
        done
    fi
fi

max_jobs=\${PARALLEL_TOOLS:-6}

_run_parallel() {
    local tools=("\$@")
    for tool in "\${tools[@]}"; do
        while (( \$(jobs -rp | wc -l) >= max_jobs )); do
            wait -n 2>/dev/null || sleep 0.1
        done
        echo "[annotate-downstream] starting: \$tool"
        "\$runner/run-\${tool}.sh" &
    done
    wait
    echo "[annotate-downstream] batch complete."
}

echo "[annotate-downstream] pre-tools  (\${#pre_tools[@]}):  \${pre_tools[*]:-none}"
echo "[annotate-downstream] post-tools (\${#post_tools[@]}): \${post_tools[*]:-none}"
echo "[annotate-downstream] max parallel: \$max_jobs   threads/tool: \${THREADS}"

(( \${#pre_tools[@]} ))  && _run_parallel "\${pre_tools[@]}"
if (( \${#post_tools[@]} )); then
    echo "[annotate-downstream] envelope inference"
    "\$runner/run-envelope.sh"
    _run_parallel "\${post_tools[@]}"
fi

echo "[annotate-downstream] all tools done."
SLURM

# ── 8. run-meta.slurm ────────────────────────────────────────────────────────
_write run-meta.slurm <<SLURM
#!/bin/bash
# GENERATED by generate-slurm-scripts.sh — do not edit by hand.
# To change settings, edit pipeline.conf.sh section 9, then run:
#   ./setup.sh --generate-slurm
#SBATCH --job-name=run-meta
#SBATCH --account=${SLURM_ACCOUNT}
#SBATCH --partition=${SLURM_PARTITION}
#SBATCH --nodes=${SLURM_META_NODES}
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=${SLURM_META_CPUS}
#SBATCH --mem=${SLURM_META_MEM}
#SBATCH --time=${SLURM_META_TIME}
#SBATCH --output=logs/annotation/run-meta-%j.out
#SBATCH --error=logs/annotation/run-meta-%j.err

# run-meta.slurm — per-genome results for every gene-called genome, from
# margie-backend's host scripts: gather → consolidation → labeling → scoring
# → fingerprint → evidence → viewer → figures, then the pangenome figures and
# the final folder layout (output/genomes/<genome>/).
#
# Submit:
#   sbatch accessory-files/slurm/run-meta.slurm
# Run a single stage (no finalize):
#   sbatch --export=ALL,STAGE=labeling accessory-files/slurm/run-meta.slurm
set -euo pipefail

cd "\$SLURM_SUBMIT_DIR"
mkdir -p logs/annotation

export THREADS=\${SLURM_CPUS_PER_TASK:-${SLURM_META_CPUS}}

runner=processing/scripts/run-individual-containers/run-meta.sh
if [[ -n "\${STAGE:-}" ]]; then
    "\$runner" --stage "\$STAGE"
else
    "\$runner"
    "\$runner" --finalize
fi
SLURM

# ── 9. gtdbtk-highmem.slurm ──────────────────────────────────────────────────
_write gtdbtk-highmem.slurm <<SLURM
#!/bin/bash
# GENERATED by generate-slurm-scripts.sh — do not edit by hand.
# To change settings, edit pipeline.conf.sh section 9, then run:
#   ./setup.sh --generate-slurm
#SBATCH --job-name=gtdbtk-highmem
#SBATCH --account=${SLURM_ACCOUNT}
#SBATCH --partition=${SLURM_GTDBTK_PARTITION}
#SBATCH --nodes=${SLURM_GTDBTK_NODES}
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=${SLURM_GTDBTK_CPUS}
#SBATCH --mem=${SLURM_GTDBTK_MEM}
#SBATCH --time=${SLURM_GTDBTK_TIME}
#SBATCH --output=logs/annotation/gtdbtk-cpu-%j.out
#SBATCH --error=logs/annotation/gtdbtk-cpu-%j.err

# gtdbtk-highmem.slurm — run GTDB-Tk classify on a high-memory node.
# Use this instead of annotate-classify.slurm when the standard partition
# does not have enough memory for GTDB-Tk placement (requires ~200 GB RAM).
set -euo pipefail

cd "\$SLURM_SUBMIT_DIR"
mkdir -p logs/annotation output/gtdbtk input

module load apptainer 2>/dev/null || module load singularity 2>/dev/null || true

export MARGIE_ACCEPT_TERMS=1
export GTDBTK_PPLACER_CPUS=1

source processing/scripts/setup-scripts/setup-databases/lib.sh
run_in_container gtdbtk \\
    --bind "\$PWD/user-input:/input:ro" \\
    --bind "\$PWD/output/gtdbtk:/output:rw" \\
    --bind "\$PWD/db/gtdbtk:/db:ro" \\
    --bind "\$PWD/input:/sort-input:rw" \\
    --bind "\$PWD/processing/containers/build/gtdbtk/entrypoint.sh:/opt/gtdbtk-entrypoint.sh:ro" \\
    --entrypoint /opt/gtdbtk-entrypoint.sh \\
    -- -i /input -o /output -d /db -t ${SLURM_GTDBTK_CPUS} \\
       --sort-dir /sort-input \\
       --top-n 20 \\
       --collection-name "collection_\$(date -u +'%Y%m%dT%H%M%SZ')"
SLURM

printf '[generate-slurm] done. All 9 SLURM scripts generated from pipeline.conf.sh section 9.\n'
